---
showSupportUrl: false
showKnownIssuesUrl: false
showReleaseNotesUrl: false
requirements:
  requiredStorage: 16
  requiredRam: 4
  check:
    - storage
    - ram
    - power
    - root
  required:
    - root
    - storage
    - ram
geoip:
  style: "none"
