modules-search: [ local, /usr/lib/x86_64-linux-gnu/calamares/modules ]

instances:
- id: partition
  module: partition
  config: partition.conf

sequence:
- show:
  - welcome
  - locale
  - keyboard
  - partition
  - users
  - summary
- exec:
  - partition
  - mount
  - unpackfs
  - machineid
  - fstab
  - locale
  - keyboard
  - localecfg
  - users
  - displaymanager
  - networkcfg
  - hwclock
  - services-systemd
  - bootloader
  - packages
  - umount
- show:
  - finished

branding: wizzaos
prompt-install: true
dont-chroot: false
